name: Metrics
on:
  schedule: [{ cron: "0 6 * * *" }]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: davasangkara
          template: classic
          base: header, activity, repositories, community
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons
          plugin_languages: yes
